[gcp_service_account]
type = "service_account"
project_id = "bmw-sales-prediction"
private_key_id = "cfa3499f793c8cacb1d478a1cb691f7cab9fc79e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCR5rmP8frDAplU
xjvWwMAkVhmRGdW3gvJkNVdLv7FvcmnmaHIaQZB43G3Fw8zjfgTzd66VjKb10600
drmrq2xmsa/aVH8HKEbBDTnYubbSky7Gw5h0M7qI8TseTdJiPU82qdwKEY/VE3Nx
+whnmu1VMVbFnK2FFrznLQdf1lfe7ZGGfR/PgvehhSDdTDf3Mg5UZXFoirvHQFbi
Vvr4bbmEsAn3VZxVfRB7OWbAlNoI4x+Y4J0TYQ2kYzUSN4urVNJQv1rXXvgzni+x
pRnUrL84Ex4B5nV0NAyOKmORQzFK0lVxW45rnmCxL7XTSunlhyACApQp7OjG2Y0i
JFw13sZNAgMBAAECgf9cdVBdrOcorXzzsjXDV+ySy4cZbLvvBW8MEdUsjhLjZdkY
22Y4eGfGpcJNLseodkdx2xd5EIGp5I5BE3H4f4JGL2fLLyMpUkkODd1zPwI5+Vpc
c+XtvZ8pUHqwL7SZKmh+nhIh2SabpcuWqqX3n4UV7fNKM8SuzX7oY2WXuJ/PVj53
Hwb9v1hp1lPSjRoUpW7RZPe+rb3CaXVBwIseIL449J6IyxelCZjb1hLQgWB80xUX
xadxydJMkToikWofi7nSIcqXGgrzpnUNoADo9pVw6V8lZkTz4zZluCfccGGLuK+n
X0mBzeWL5BDOqyMM+znhA/rA2UoDpTBgaJ7IKd0CgYEAy12ayfCpnaY42zN867F4
uM+/OjPm4KDgCX6S0MfPE2MBSeyDCN4r2L6l0esuv89TjDwEYQebt0o9Uiy4F1EI
PupxFbSJzIfiZQhddB2T17v5YZjs2MEnoXu6zCl1RdxFI2oB9S/Nz3WIAmZcxYfo
eLQmNCPKa8sjAVwlSdY6Zj8CgYEAt6m0KQYMKoJahNWzIn15CiJbicUo+eWt41Y0
J1xZ7BpjvdAHPTLk7OJ+NAjNV2nrDMGYqJYO1z7zh/axkZuqpOhKRPeqx5DI++0B
CIcU2QJMZ/TtqvPc8GNis58wOSRYZCzjGV0NG6o1Hno3bMoxk9w6TqqjkwxyP/62
ANYXKHMCgYA8jmv4NASd4BBQHX3WRSt4hMwhjbDzNJRh32Hib40W7cVFePrv2hBe
Yy7HWmu6TAdJ29lF91kD9ERcQtqyfrug2HjCCNd7ov7kLOB/IguTEvNIf5wPUzz0
1f4iqzmzisq/p+JbW1fCrfHJHSgE3dp4jtRNdFbjUELlNcYYvYT4SwKBgHwyAMcg
9McmIMnkrF7tVBU7SIUwUtYxr1WkrF3VgGU9Lydi7hI/QTjCrC7JqPmsgSq+G1od
Jun9Ard1ZXweNNWQ0vAyPkT3LkHVcbZvifR5Lmu536GTiFryCgOG6Rgq8K7E/8jd
+Ig1n/f9E0+4pq/i43bgwv4kE3oc5rxICZ7rAoGAEvukgScpwFF/TUy58GxJzEYw
DLEAukaHVYUQHhZ9eXJotcDNf1AUg8lMq9hOcKZbG3dsA3JVtG7IQaEC/rk6GYSd
T66Q1ptMBSD0FmE4g55y+U1f/WlFA2Nk8u6kCKdhqoZUVQJlKczuvb8z0R5YZCpu
3BTmLjpNlr8iBrxnx+U=
-----END PRIVATE KEY-----"""
client_email = "bmw-367@bmw-sales-prediction.iam.gserviceaccount.com"
client_id = "116940136091704930288"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bmw-367%40bmw-sales-prediction.iam.gserviceaccount.com"
universe_domain = "googleapis.com"